name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm install

      - run: npm test
        env:
          CI: true

      - name: Set environment variables securely
        run: |
          echo "JWT_SECRET=$(secrets.JWT_SECRET)" >> $GITHUB_ENV
        env:
          secrets: ${{ secrets }}

      - name: Install Java 17 (AdoptOpenJDK) (existing)
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Build and test (existing)
        run: mvn clean test

      - name: Deploy artifacts
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: mvn deploy
