name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setar variáveis de ambiente
        run: echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV

      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Compilar
        run: mvn clean test

      - name: Artefatos
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: mvn deploy
